---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: config-syncer
  namespace: config-syncer
spec:
  chart:
    spec:
      chart: config-syncer
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: config-syncer
        namespace: flux-system
      version: '>=0.14.5-0'
  interval: 1h0m0s
  releaseName: config-syncer
  targetNamespace: config-syncer
