---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: postgres
spec:
  encryptedData:
    password: AgDNNnC3ApNpNICS1FJx6MAAYPIZfhcSa9cV5v9dZ4kBQ3gwLENVv10gQ7rq97mTBICS0lmRoIn/rFrM25hvdFJCJ57xvXS+m0EsiUjYBQ8t55250OlW4uKhgl4C5V2UMyYynWyl97wpHdFBInCR/DufPFQ3JSSoiMPoFKPdayY2ncwEdm6NiWOCNOQwfv4scBuB3MQKrEoAQLIJPJVg2Cxo1J9Y8XBSGR13ec2Y7qSJfVec93zjja1XJkVN/H7yA4a8bS1zCYZCtbpkWg25nx9yg+AYVKGC8aLiEFooUCrIAra0/oZ/GbwVqkuNA+kCilyTNJK4om4uekOhn6LFYP3Pqhdbl6oyABZJzb163OB9rWpQwxieJk51x/zPUbbYxHMLV7S58HnOEmK7RIcICl8TVKSCq4KX9riZxK9PoPDz6gDZh/+xgUgRBBIHw3x5EyfY/NjPoLbZjZoGzMWqU3xngfWE52wZSzSVASMF68JyqtF3zYjowLRwniHNvsFF/ixiAkXzO8XjdNMwRXWPDdwsJ57+kydgDjdXBIWSjYxn3CsXQFK2MN9etYXmgqfujjxrLzLnirhtH/P9dUsZz9yrQMYIzc0ZG9DJu6TdF/PIrOLphf01206UugL2gARvZ1IltLtEO7A2sa5/nz7bwC6MKUy/51biIS1Sv82yq5ovXqZnoB/RDzE6eRN8io7j3vL4yN844KevnS98
  template:
    metadata:
      creationTimestamp: null
      name: postgres-password
      namespace: postgres
