apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-cred: "secret/postgres/cred"
        vault.hashicorp.com/agent-inject-template-cred: |
          {{- with secret "secret/postgres/cred" }}
          POSTGRES_USER={{ .Data.username }}
          POSTGRES_PASSWORD={{ .Data.password }}
          {{- end }}
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: postgres
        image: postgres:15.5
        ports:
        - containerPort: 5432
