apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres
  annotations:
    vault.hashicorp.com/role: "postgres"
    vault.hashicorp.com/tls-skip-verify: "true"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-secret-credentials: "secret/postgres/cred"
    vault.hashicorp.com/agent-inject-template-credentials: |
      {{- with secret "secret/postgres/cred" }}
      POSTGRES_USER={{ .Data.username }}
      POSTGRES_PASSWORD={{ .Data.password }}
      {{- end }}
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: postgres
        image: postgres:15.5
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: vault-secret-credentials
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vault-secret-credentials
                key: POSTGRES_PASSWORD
