---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/production/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
