---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  interval: 1h0m0s
  releaseName: sealed-secrets-controller
  chart:
    spec:
      chart: sealed-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
      version: '>=2.14.0-0'
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
